import {
  ShoppingBag,
  AreaChart,
  History,
  ClipboardList,
  Archive,
  Table as TableIcon,
  Users,
  Truck,
  NotebookText,
  Briefcase,
  Settings as SettingsIcon,
} from 'lucide-react';
import type { ActiveView, Permission } from './types';

export const UI_TEXT = {
  sales: { en: "Sales", ar: "المبيعات" },
  salesHistory: { en: "Sales History", ar: "سجل المبيعات" },
  dashboard: { en: "Dashboard", ar: "لوحة التحكم" },
  products: { en: "Products", ar: "المنتجات" },
  productsAndRecipes: { en: "Products & Recipes", ar: "المنتجات والوصفات" },
  customers: { en: "Customers", ar: "العملاء" },
  purchases: { en: "Purchases & Suppliers", ar: "المشتريات والموردين" },
  inventory: { en: "Inventory", ar: "المخزون" },
  shifts: { en: "Shifts & Cash", ar: "الشفتات والخزينة" },
  expenses: { en: "Expenses", ar: "المصروفات" },
  cashDrawer: { en: "Cash Drawer", ar: "الخزينة" },
  settings: { en: "Settings", ar: "الإعدادات" },
  tables: { en: "Tables", ar: "الطاولات" },
  deliveryReps: { en: "Delivery Reps", ar: "مندوبي التوصيل" },
  transactionSuccess: { en: "Transaction successful!", ar: "تمت العملية بنجاح!" },
  transactionSuccessDesc: { en: (id: string) => `Sale ID: ${id}`, ar: (id: string) => `رقم الفاتورة: ${id}`},
  orderHeld: { en: 'Order held successfully!', ar: 'تم تعليق الطلب بنجاح!' },
  quickServeLite: { en: "RMS POS", ar: "RMS POS" },
  searchPlaceholder: { en: "Search by name or barcode...", ar: "ابحث بالاسم أو الباركود..." },
  menu: { en: "Menu", ar: "القائمة" },
  allCategories: { en: 'All Categories', ar: 'كل الفئات' },
  selectCategory: { en: 'Select a category', ar: 'اختر فئة' },
  selectOrderTypePrompt: { en: 'Select an Order Type', ar: 'اختر نوع الطلب' },
  selectOrderTypePromptDesc: { en: 'Please select an order type to begin.', ar: 'يرجى اختيار نوع الطلب للبدء.' },
  quickServe: { en: "Quick Serve", ar: "خدمة سريعة" },
  dineIn: { en: "Dine-in", ar: "صالة" },
  takeaway: { en: "Takeaway", ar: "سفري" },
  delivery: { en: "Delivery", ar: "توصيل" },
  customerRequired: { en: 'Customer Required', ar: 'العميل مطلوب' },
  customerRequiredDesc: { en: 'Please select or add a customer for this delivery order.', ar: 'يرجى اختيار أو إضافة عميل لطلب التوصيل هذا.' },
  confirmCustomer: { en: 'Confirm Customer & Add Items', ar: 'تأكيد العميل وإضافة الأصناف' },
  noActiveShift: { en: 'No Active Shift', ar: 'لا يوجد شفت نشط' },
  noActiveShiftDesc: { en: 'You must start a new shift to use the POS.', ar: 'يجب أن تبدأ شفتًا جديدًا لاستخدام نقطة البيع.' },
  switchOrder: { en: 'Switch Order', ar: 'تغيير الطلب' },
  unauthorized: { en: 'Unauthorized Access', ar: 'وصول غير مصرح به' },
  unauthorizedDesc: { en: 'You do not have permission to view this page.', ar: 'ليس لديك الصلاحية لعرض هذه الصفحة.' },
};

export const VIEW_OPTIONS: { value: ActiveView; label: keyof typeof UI_TEXT; icon: React.ElementType, permission?: Permission }[] = [
    { value: 'sales', label: 'sales', icon: ShoppingBag },
    { value: 'dashboard', label: 'dashboard', icon: AreaChart, permission: 'access_dashboard' },
    { value: 'history', label: 'salesHistory', icon: History, permission: 'access_sales_history' },
    { value: 'products', label: 'productsAndRecipes', icon: ClipboardList, permission: 'access_products' },
    { value: 'inventory', label: 'inventory', icon: Archive, permission: 'access_inventory' },
    { value: 'tables', label: 'tables', icon: TableIcon, permission: 'access_tables' },
    { value: 'customers', label: 'customers', icon: Users, permission: 'access_customers' },
    { value: 'purchases', label: 'purchases', icon: Truck, permission: 'access_purchases' },
    { value: 'deliveryReps', label: 'deliveryReps', icon: NotebookText, permission: 'access_delivery' },
    { value: 'shifts', label: 'shifts', icon: Briefcase, permission: 'access_shifts' },
    { value: 'settings', label: 'settings', icon: SettingsIcon, permission: 'access_settings' },
];

export const PERMISSIONS_LIST: { key: Permission, text: { en: string, ar: string }}[] = [
  { key: 'access_dashboard', text: { en: 'Access Dashboard', ar: 'الوصول إلى لوحة التحكم' } },
  { key: 'access_sales_history', text: { en: 'Access Sales History', ar: 'الوصول إلى سجل المبيعات' } },
  { key: 'access_products', text: { en: 'Manage Products & Recipes', ar: 'إدارة المنتجات والوصفات' } },
  { key: 'access_inventory', text: { en: 'Manage Inventory', ar: 'إدارة المخزون' } },
  { key: 'access_customers', text: { en: 'Manage Customers', ar: 'إدارة العملاء' } },
  { key: 'access_purchases', text: { en: 'Manage Purchases & Suppliers', ar: 'إدارة المشتريات والموردين' } },
  { key: 'access_delivery', text: { en: 'Manage Delivery Reps', ar: 'إدارة مندوبي التوصيل' } },
  { key: 'access_shifts', text: { en: 'Manage Shifts, Cash & Expenses', ar: 'إدارة الشفتات، الخزينة والمصروفات' } },
  { key: 'access_tables', text: { en: 'Manage Tables', ar: 'إدارة الطاولات' } },
  { key: 'access_settings', text: { en: 'Access Settings', ar: 'الوصول إلى الإعدادات' } },
];
