import type { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: "Espresso",
    nameAr: "اسبريسو",
    price: 25.00,
    image: "https://picsum.photos/400/300?random=1",
    dataAiHint: "coffee cup",
  },
  {
    id: 2,
    name: "Latte",
    nameAr: "لاتيه",
    price: 35.50,
    image: "https://picsum.photos/400/300?random=2",
    dataAiHint: "latte art",
  },
  {
    id: 3,
    name: "Croissant",
    nameAr: "كرواسون",
    price: 22.75,
    image: "https://picsum.photos/400/300?random=3",
    dataAiHint: "fresh croissant",
  },
  {
    id: 4,
    name: "Cheesecake",
    nameAr: "تشيز كيك",
    price: 45.00,
    image: "https://picsum.photos/400/300?random=4",
    dataAiHint: "slice cheesecake",
  },
  {
    id: 5,
    name: "Iced Tea",
    nameAr: "شاي مثلج",
    price: 30.25,
    image: "https://picsum.photos/400/300?random=5",
    dataAiHint: "iced tea",
  },
  {
    id: 6,
    name: "Muffin",
    nameAr: "مافن",
    price: 28.00,
    image: "https://picsum.photos/400/300?random=6",
    dataAiHint: "chocolate muffin",
  },
    {
    id: 7,
    name: "Cappuccino",
    nameAr: "كابتشينو",
    price: 32.00,
    image: "https://picsum.photos/400/300?random=7",
    dataAiHint: "cappuccino foam",
  },
  {
    id: 8,
    name: "Orange Juice",
    nameAr: "عصير برتقال",
    price: 28.50,
    image: "https://picsum.photos/400/300?random=8",
    dataAiHint: "orange juice",
  },
  {
    id: 9,
    name: "Club Sandwich",
    nameAr: "كلوب سندويتش",
    price: 55.00,
    image: "https://picsum.photos/400/300?random=9",
    dataAiHint: "club sandwich",
  },
];
